package com.ladestitute.chaocubed.util;

public enum ChaoVariant {
    NORMAL,
    NORMAL_MONOTONE,
    NORMAL_TWOTONE,
    SHINY_NORMAL_TWOTONE,
    BRIGHT_NORMAL_TWOTONE,
    SHINY_NORMAL_MONOTONE,
    BRIGHT_NORMAL_MONOTONE,
    NORMAL_TWOTONE_NEUTRAL_POWER

    // PLACEHOLDER ENTRIES TO COVER ALL JEWEL TYPES AND SHINY/TONE/BRIGHT/ETC COMBOS
    // WHEN ADDING NEW CHAO VARIANTS

    // PLACEHOLDER_TEXTURE,
    // PLACEHOLDER_SHINY_COLOR_MONOTONE,
    // PLACEHOLDER_SHINY_COLOR_TWOTONE,
    // PLACEHOLDER_BRIGHT_COLOR_MONOTONE,
    // PLACEHOLDER_BRIGHT_COLOR_TWOTONE,
    // PLACEHOLDER_COLOR_MONOTONE,
    // PLACEHOLDER_COLOR_TWOTONE
}
